## Numpy

In [1]:
import numpy as np 

### Numpy vectorizes the operations
$$x = \begin{bmatrix} 1, 2, 3 \end{bmatrix}, y = \begin{bmatrix} 4, 5, 6 \end{bmatrix}, x+y=?$$

In [2]:
x = np.array([1,2,3])
y = np.array([4,5,6])
x + y 

array([5, 7, 9])

In [3]:
# Numpy array vs n-dimensional list

x = np.array([1,2,3])
print(x.shape)

x = np.array([[1,2,3], [4,5,6]])
print(x.shape)

(3,)
(2, 3)


In [4]:
# Transpose
x = np.array([[1,2,3], [4,5,6]])
x, x.T 

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [5]:
# reshape
x.reshape((1,6)), x.reshape((6,1)), x.reshape((2,3))

(array([[1, 2, 3, 4, 5, 6]]),
 array([[1],
        [2],
        [3],
        [4],
        [5],
        [6]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [6]:
# zeros_like and ones_like
z = np.zeros_like(x)
z

array([[0, 0, 0],
       [0, 0, 0]])

In [7]:
# Numpy array <-> python list
z.tolist()

[[0, 0, 0], [0, 0, 0]]

In [8]:
# Mean, variance, std
x.mean(), x.var(), x.std()

(3.5, 2.9166666666666665, 1.707825127659933)

In [9]:
# Mean by dimension / axis
x.mean(axis=0), x.mean(axis=1)

(array([2.5, 3.5, 4.5]), array([2., 5.]))

In [9]:
# Broadcasting
print(x)
x + np.array([1,2,3])

[[1 2 3]
 [4 5 6]]


array([[2, 4, 6],
       [5, 7, 9]])

In [10]:
x + np.array([[1,2,3], [1,2,3]])

array([[2, 4, 6],
       [5, 7, 9]])

### Review questions

Write a function that computes the matrix multiplication of two matrices (written in numpy arrays) without using `numpy.matmul`. This function should first check whether the arrays are two-dimensional. If not, throw an error.  
Then check whether the second dimension of the first matrix matches the first dimension of the second matrix. If not, throw an error.  
Then, compute the matrix multiplication result and return it.